<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="{{ public_path('css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ public_path('css/custom.css') }}">


    <style>

    </style>
</head>

<body>
    <div class="row">

        <div class="col-xs-3" style="">
            <img src="{{ Auth::user()->branch->img_path }}" height="70" width="100" />
        </div>

        <div class="col-xs-6">

            @if ($data[0]->branch->business_name)
                <p class="company-name">
                    {{ $data[0]->branch->business_name }}
                </p>
            @endif
        </div>
        {{-- <div class="col-xs-3 invoice doc-type" style="position: absolute"><h3>INVOICE</h3> </div> --}}
    </div>


    <div class="row bg-dark" style="margin-top:2rem;text:center;">
        <div class="col-xs-4">
            <h4><b class="title_2"> Client</b></h4>
        </div>
        <div class="col-xs-4"></div>
        <div class="col-xs-4">
            <h4><b class="title_2"> Vendor</b></h4>
        </div>
    </div>

    <div class="row" style="padding-top:2rem;">

        <div class="col-xs-4 left-cont">

            <p style="margin-left:0.6rem"><b>


                    <h2><b class="invoice doc-type">CREDIT NOTE</b></h2>
                    <p>{{ $data[0]->invoice->customer->company_name }}</p>

                    @if ($data[0]->invoice->customer->company_phone)
                        <p>Phone: {{ $data[0]->invoice->customer->company_phone }} </p>
                    @endif
                    @if ($data[0]->invoice->customer->company_email)
                        <p>Email:{{ $data[0]->invoice->customer->company_email }} </p>
                    @endif
                    @if ($data[0]->invoice->customer->country)
                        <p>Country:
                            {{ $data[0]->invoice->customer->country }}/{{ $data[0]->invoice->customer->city }} </p>
                    @endif
                    @if ($data[0]->invoice->customer->postal_address)
                        <p>{{ $data[0]->invoice->customer->postal_address }} /
                            {{ $data[0]->invoice->customer->address }} </p>
                    @endif
                    @if ($data[0]->invoice->customer->pin)
                        <p>Client PIN: {{ $data[0]->invoice->customer->pin }} </p>
                    @endif

                    <p> Credit No:{{ substr($data[0]->credit_no, 7) }}</p>

                    <p class="item"> Invoice No: {{ $data[0]->invoice_no }}</p>

                    <p> Credit Date: {{ $data[0]->credit_date }}</p>


        </div>
        <div class="col-xs-4"></div>
        <div class="col-xs-4 right-cont">


            <h3>From</h3>
            <p> {{ $data[0]->branch->business_name }}</p>
            @if ($data[0]->branch->branch)
                <p>Branch: {{ $data[0]->branch->branch }}</p>
            @endif

            @if ($data[0]->branch->postal_address)
                <p>Address: {{ $data[0]->branch->postal_address }}</p>
            @endif
            @if ($data[0]->branch->address)
                <p> {{ $data[0]->branch->address }}</p>
            @endif
            @if ($data[0]->branch->kra_pin)
                <p>Document PIN: {{ $data[0]->branch->kra_pin }}</p>
            @endif
            <p> Generated By: {{ $data[0]->user->name }}</p>

        </div>

    </div>


    <hr>
   
    <table class="table ">
        <thead class="bg-dark">
            <tr>
                <td><b class="title_2">Code</b></td>
                <td><b class="title_2">Item Name</b></td>


                <td><b class="title_2">Qty</b></td>
                <td><b class="title_2">Price</b></td>
                <td><b class="title_2">Total</b></td>
            </tr>
        </thead>
        <tbody>
            @php($total = 0)
            @php($total_tax = 0)
            @foreach ($data as $item)
                <tr>
                    <td class="item">{{ $item->invoice->stock->code }}</td>
                    <td class="item">{{ $item->invoice->stock->name }}</td>

                    <td class="item">{{ $item->qty }}</td>
                    <td class="item">{{ number_format($item->price, 2) }}</td>
                    <td class="item">{{ number_format($item->line_total, 2) }}</td>
                    @php($total += $item->line_total)
                    @php($total_tax += $item->row_vat)
                </tr>
            @endforeach

            <tr>
                <td colspan="4">
                    <b class="totals"> VAT Amount</b>
                </td>
                <td>
                    <b class="totals"> {{ number_format(round($total_tax), 2) }}</b>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <b class="totals"> Credit Amount</b>
                </td>
                <td>
                    <b class="totals"> {{ number_format(round($total), 2) }}</b>
                </td>
            </tr>
            <tr>
                <td>
                    @if ($data[0]->notes)
                        <p class="title_2"> {{ $data[0]->notes }}</p>
                    @endif
                </td>
            </tr>
        </tbody>
    </table>


</body>

</html>
