<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
    <style>
        .table-bordered table {
            border-collapse: collapse;
        }

        .table-bordered th,
        .table-bordered td,
        .table-bordered tr {
            /* border-bottom: 1px solid rgb(14, 13, 13);
            border-right: 1px solid rgb(14, 13, 13); */

        }

        .table-bordered td {
            padding: 4px !important;
        }

        .table-bordered thead {
            border-top: 1px solid rgb(14, 13, 13);
        }

        table {
            width: 100% !important;
        }

        .table-address {
            width: 100% !important;
            margin-bottom: 0rem;
            margin-top: -14px;
        }

        .right-cont {}

        .left-cont p {
            line-height: 0.6em;
            font-weight: 600;
        }

        .right-cont span {
            float: right;
            margin-right: 1rem;

        }

        .right-cont span p {
            line-height: 0.6em;
            font-weight: 600;
        }

        .table-address p {
            font-size: 0.8em;
        }

        .invoice {
            text-align: center;
            color: rgb(83, 81, 81);
            font-weight: 700;
            font-size: 1.4rem;
        }

        .company-name {
            color: #9A631D !important;
            font-family: 'Times New Roman', Times, serif !important;
            font-weight: 900 !important;
            font-size: 2.4.0rem !important;

        }

        .company-add {
            color: rgb(211, 79, 79);
            font-style: italic;
            font-weight: 600;
            font-size: 1rem;
        }

        .top-title {
            margin-left: -34px !important;

        }
    </style>
</head>

<body>
    <table>

        <tr>
            <td class="top-title">
                {{-- <center><img src="{{ url('/images/logo.png') }}" height="120" width="100"/></center> --}}
                
                    <img src="{{ Auth::user()->branch->img_path }}" style="margin-left:2rem" height="70" width="100" />

            </td>
            <td>
                <div><b class="company-name">
                        @if($data[0]['branch']->business_name)
                        <p class="company-name">
                            {{ $data[0]['branch']->business_name}}
                        </p>
                        @endif
                    </b>
                </div>
            </td>
        </tr>

    </table>
    <table class="table-address">
        <tr>
            <td class="left-cont">
                <h3>Company</h3>
                <p> {{ $data[0]['branch']->business_name}}</p>
                @if($data[0]['branch']->branch)
                <p>Branch: {{ $data[0]['branch']->branch}}</p>
                @endif

                @if($data[0]['branch']->postal_address)
                <p>Address: {{ $data[0]['branch']->postal_address}}</p>
                @endif
                @if($data[0]['branch']->address)
                <p> {{ $data[0]['branch']->address}}</p>
                @endif
                <p><b> Generated By: </b> {{ $data[0]['user']->name}}</p>

            </td>
            <td class="right-cont">
                <span>
                    <p>
                        <h4>Customer: </h4> {{ $data[0]['customer']->company_name}}
                    </p><br>

                    @if($data[0]['customer']->company_phone) <p><b>Phone: </b>{{ $data[0]['customer']->company_phone}} </p>
                    @endif

                    @if($data[0]['customer']->company_email) <p><b>Email: </b>{{ $data[0]['customer']->company_email}} </p>
                    @endif
                    @if($data[0]['customer']->country) <p><b>Country:
                        </b>{{ $data[0]['customer']->country}}/{{ $data[0]['customer']->city}} </p>
                    @endif
                    @if($data[0]['customer']->postal_address) <p>{{ $data[0]['customer']->postal_address}} /
                        {{ $data[0]['customer']->address}} </p>
                    @endif

                </span>
            </td>
        </tr>
    </table>
    <table>
        <tr>

            <td>
                <p> <b>Statement Date: </b>{{ date('Y/m/d h:i:', time()) }}</p>
            </td>
        </tr>
    </table>

    <table>
        <tr>
            <td class="invoice">
                <p>CUSTOMER STATEMENT</p>
            </td>
        </tr>

    </table>

    <table class="table table-bordered">
        <thead>
            <tr>
                <td style="width:15%"><b> Date.</b></td>
                <td><b> Ref No.</b></td>
                <td><b>Type</b></td>
                <td><b>Description</b></td>
                <td><b>Debit</b></td>
                <td><b>Credit</b></td>

                <td><b>Balance</b></td>

            </tr>
        </thead>
        <tbody>
            @php($total = 0)

            @foreach ($data as $item)
            <tr>
                <td>{{ $item['entry_date']}}</td>
                <td>{{ $item['ref']}}</td>
                <td>{{ $item['type']}}</td>
                <td>{{ $item['description']}}</td>
                <td>{{ number_format(($item['debit']),2)}}</td>
                <td>{{ number_format(($item['credit']),2)}}</td>

                <td>{{ number_format(($item['balance']),2)}}</td>

            </tr>
            @endforeach


        </tbody>
    </table>
    <table style="   position: fixed;
    bottom: 24px; border: 1px solid rgb(14, 13, 13);border-radius:4px;">
        <tr>
            <td>
                180 days
            </td>
            <td>
                150 days
            </td>
            <td>
                120 days
            </td>
            <td>
                90 days
            </td>
            <td>
                60 days
            </td>
            <td>
                30 days
            </td>
            <td>
                Current
            </td>

        </tr>
        <tr>
            <td>
                {{number_format(($one_80),2)}}
            </td>
            <td>

                {{number_format(($one_50),2)}}
            </td>
            <td>
                {{number_format(($one_20),2)}}
            </td>
            <td>
                {{number_format(($ninety),2)}}
            </td>
            <td>
                {{number_format(($sixty),2)}}

            </td>
            <td>
                {{number_format(($thirty),2)}}
            </td>
            <td>
                {{number_format(($current),2)}}
            </td>

        </tr>
    </table>
</body>

</html>