<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
    <style>
        .table-bordered table {
            border-collapse: collapse;
        }

        .table-bordered th,
        .table-bordered td,
        .table-bordered tr {
            /* border-bottom: 1px solid rgb(14, 13, 13);
            border-right: 1px solid rgb(14, 13, 13); */

        }

        .table-bordered td {
            padding: 4px !important;
        }

        .table-bordered thead {
            border-top: 1px solid rgb(14, 13, 13);
        }

        table {
            width: 100% !important;
        }

        .table-address {
            width: 100% !important;
            margin-bottom: 0rem;
            margin-top: -14px;
        }

        .right-cont {}

        .left-cont p {
            line-height: 0.6em;
            font-weight: 600;
        }

        .right-cont span {
            float: right;
            margin-right: 1rem;

        }

        .right-cont span p {
            line-height: 0.6em;
            font-weight: 600;
        }

        .table-address p {
            font-size: 0.8em;
        }

        .invoice {
            text-align: center;
            color: rgb(83, 81, 81);
            font-weight: 700;
            font-size: 1.4rem;
        }

        .company-name {
            color: #9A631D !important;
            font-family: 'Times New Roman', Times, serif !important;
            font-weight: 900 !important;
            font-size: 3.0rem !important;


        }

        .company-add {
            color: rgb(211, 79, 79);
            font-style: italic;
            font-weight: 600;
            font-size: 1rem;
        }

        .doc-type {
            margin-top: -16px;
            margin-bottom: -14px
        }

        .top-title {
            margin-left: -34px !important;

        }
    </style>
</head>

<body>
    <table>
        <tr>

            <td class="top-title">
              

                <center> <img src="{{ Auth::user()->branch->img_path }}" height="70" width="100" /></center>
            </td>
            <td>
                <div><b class="company-name">
                        @if($data[0]->branch->business_name)
                        <p class="company-name">
                            {{ $data[0]->branch->business_name}}
                        </p>
                        @endif
                    </b>
                </div>

            </td>

        </tr>
        <tr>
            <td>

            </td>
        </tr>
    </table>
    <table class="table-address">
        <tr>
            <td class="left-cont">
                <h3>From</h3>
                <p> {{ $data[0]->branch->business_name}}</p>
                @if($data[0]->branch->branch)
                <p>Branch: {{ $data[0]->branch->branch}}</p>
                @endif

                @if($data[0]->branch->postal_address)
                <p>Address: {{ $data[0]->branch->postal_address}}</p>
                @endif
                @if($data[0]->branch->address)
                <p> {{ $data[0]->branch->address}}</p>
                @endif
                <p><b> Generated By: </b> {{ $data[0]->user->name}}</p>
            </td>
            <td class="right-cont">
                <span>
                    <h4>TO</h4>
                    <p>{{ $data[0]->customer->company_name}}</p>

                    @if($data[0]->customer->company_phone)
                    <p><b>Phone: </b>{{ $data[0]->customer->company_phone}} </p>
                    @endif
                    @if($data[0]->customer->company_email)
                    <p><b>Email: </b>{{ $data[0]->customer->company_email}} </p>
                    @endif
                    @if($data[0]->customer->country)
                    <p><b>Country: </b>{{ $data[0]->customer->country}}/{{ $data[0]->customer->city}} </p>
                    @endif
                    @if($data[0]->customer->postal_address)
                    <p>{{ $data[0]->customer->postal_address}} / {{ $data[0]->customer->address}} </p>
                    @endif

                </span>
            </td>
        </tr>
    </table>
    <table class="table-to-address">
        <tr>
            <td class="left-cont">

            </td>
            <td class="right-cont">


            </td>
        </tr>
    </table>
    <table class="doc-type">
        <tr>
            <td class="invoice">
                <p>INVOICE</p>
            </td>
        </tr>
    </table>
    <table>
        <tr>
            <td>
                <p> <b>Order No:</b>{{$data[0]->order_no}}</p>
            </td>
            <td>
                <p> <b>Invoice No:</b>{{$data[0]->invoice_no}}</p>
            </td>
            <td>
                <p> <b>Invoice Date:</b>{{$data[0]->invoice_date}}</p>
            </td>
        </tr>
    </table>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td><b>Code</b></td>
                <td><b>Item Name</b></td>
                <td><b>Description</b></td>

                <td><b>Qty</b></td>
                <td><b>Price</b></td>
                <td><b>Total</b></td>
            </tr>
        </thead>
        <tbody>
            @php($total = 0)
            @foreach ($data as $item)
            <tr>
                <td>{{ $item->stock->code}}</td>
                <td>{{ $item->stock->product_name}}</td>
                <td>{{ $item->stock->description}}</td>

                <td>{{ $item->qty}}</td>
                <td>{{ number_format($item->price,2)}}</td>
                <td>{{ number_format(($item->row_total),2)}}</td>
                @php($total += $item->row_total)
            </tr>
            @endforeach

            <tr>
                <td colspan="5">
                    <b> INVOICE TOTAL</b>
                </td>
                <td>
                    <b> {{number_format($total,2) }}</b>
                </td>
            </tr>
        </tbody>
    </table>

</body>

</html>