<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="{{ public_path('css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ public_path('css/custom.css') }}">


    <style>

    </style>
</head>

<body>
    <div class="row">

        <div class="col-xs-3" style="">
            <img src="{{ Auth::user()->branch->img_path }}" height="70" width="100" />
        </div>

        <div class="col-xs-8">

            @if ($data[0]->branch->business_name)
                <p class="company-name">
                    {{ $data[0]->branch->business_name }}
                </p>
            @endif
        </div>
        {{-- <div class="col-xs-3 invoice doc-type" style="position: absolute"><h3>INVOICE</h3> </div> --}}
    </div>


    <div class="row bg-dark" style="margin-top:2rem;text:center;">
        <div class="col-xs-4">
            <h4><b class="title_2"> Client</b></h4>
        </div>
        <div class="col-xs-4"></div>
        <div class="col-xs-4">
            <h4><b class="title_2"> Vendor</b></h4>
        </div>
    </div>

    <div class="row" style="padding-top:2rem;">

        <div class="col-xs-4 left-cont">

            <p style="margin-left:0.6rem"><b>


                    <h2><b class="invoice doc-type">INVOICE</b></h2>
                    <p><b>{{ $data[0]->customer->company_name }}</b></p>

                    @if ($data[0]->customer->company_phone)
                        <p>Tel: {{ $data[0]->customer->company_phone }} </p>
                    @endif
                    @if ($data[0]->customer->company_email)
                        <p>Email: {{ $data[0]->customer->company_email }} </p>
                    @endif
                    @if ($data[0]->customer->country)
                        <p>Country: {{ $data[0]->customer->country }}/{{ $data[0]->customer->city }} </p>
                    @endif
                    @if ($data[0]->customer->postal_address)
                        <p>{{ $data[0]->customer->postal_address }} / {{ $data[0]->customer->address }} </p>
                    @endif
                    @if ($data[0]->customer->pin)
                        <p>Client PIN: {{ $data[0]->customer->pin }} </p>
                    @endif

                    <p class="item"> Order No: {{ $data[0]->order_no }}</p>

                    <p class="item"> Invoice No: {{ $data[0]->invoice_no }}</p>

                    <p class="item"> Invoice Date: {{ $data[0]->invoice_date }}</p>


        </div>
        <div class="col-xs-4 right-cont">
            @if ($data[0]->notes)
                <p>CU Invoice NO.: {{ $data[0]->notes }} </p>
            @endif
            @if ($data[0]->d_note)
                <p>D. Note: {{ $data[0]->d_note }} </p>
            @endif
        </div>
        <div class="col-xs-4 right-cont">


            <h3>From</h3>
            <p> {{ $data[0]->branch->business_name }}</p>
            @if ($data[0]->branch->branch)
                <p>Branch: {{ $data[0]->branch->branch }}</p>
            @endif

            @if ($data[0]->branch->postal_address)
                <p>Address: {{ $data[0]->branch->postal_address }}</p>
            @endif
            @if ($data[0]->branch->address)
                <p> {{ $data[0]->branch->address }}</p>
            @endif
            @if ($data[0]->branch->kra_pin)
                <p>Document PIN: {{ $data[0]->branch->kra_pin }}</p>
            @endif
           
            <p> Generated By: {{ $data[0]->user->name }}</p>
            @if ($data[0]->branch->till_no)
            <div class="payment"  > <b> {{ $data[0]->branch->till_no }}</b></div>
         @endif
        </div>

    </div>

    {{-- <div class="row">
        <div class="col-xs-12 invoice doc-type">
            <h3>INVOICE</h3>
        </div>
    </div> --}}

    <hr>


    <table class="table ">
        <thead class="bg-dark">
            <tr>
                <td><b class="title_2">Code</b></td>
                <td><b class="title_2">Item Name</b></td>


                <td><b class="title_2">Qty</b></td>

                <td><b class="title_2">Price</b></td>
                <td><b class="title_2">Disc</b></td>
                <td><b class="title_2">Total</b></td>
            </tr>
        </thead>
        <tbody>
            @php($total = 0)
            @php($total_tax = 0)
            @php($total_discount = 0)
            @foreach ($data as $item)
                <tr>
                    <td class="item">{{ $item->stock->code }}</td>
                    <td class="item">{{ $item->stock->product_name }}</td>


                    <td class="item">{{ $item->qty }}</td>

                    <td class="item">{{ number_format($item->price, 2) }}</td>
                    <td class="item">-{{ $item->discount }}</td>
                    <td class="item">{{ number_format($item->row_total, 2) }}</td>
                    @php($total += $item->row_total)
                    @php($total_tax += $item->tax_amount)
                    @php($total_discount += $item->discount) 
                </tr>
            @endforeach
            <tr>
                <td colspan="4"></td>
                <td >
                    <b class="totals"> Sub Total</b>
                </td>
                <td>
                    <b class="totals"> {{ number_format(round($total-$total_tax), 2) }}</b>
                </td>
            </tr>
            <tr>
                <td colspan="4"></td>
                <td >
                    <b class="totals"> VAT Total</b>
                </td>
                <td>
                    <b class="totals"> {{ number_format(round($total_tax), 2) }}</b>
                </td>
            </tr>
            <tr>
                <td colspan="4"></td>
                <td >
                    <b class="totals"> Discount Amount</b>
                </td>
                <td>
                    <b class="totals"> {{ number_format(round($total_discount), 2) }}</b>
                </td>
            </tr>
            <tr>
                <td colspan="4"></td>
                <td >
                    <b class="totals"> Invoice Total</b>
                </td>
                <td>
                    <b class="totals"> {{ number_format(round($total), 2) }}</b>
                </td>
            </tr>
        </tbody>
    </table>


</body>

</html>
