<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" type="text/css" href="{{ public_path('css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ public_path('css/custom.css') }}">


    <style>

    </style>
</head>

<body>
    <div class="row">

        <div class="col-xs-3" style="">
            <img src="{{ Auth::user()->branch->img_path }}" height="70" width="100" />
        </div>

        <div class="col-xs-6">

            @if ($data[0]->branch->business_name)
                <p class="company-name">
                    {{ $data[0]->branch->business_name }}
                </p>
            @endif
        </div>
        {{-- <div class="col-xs-3 invoice doc-type" style="position: absolute"><h3>INVOICE</h3> </div> --}}
    </div>


    <div class="row bg-dark" style="margin-top:2rem;text:center;">
        <div class="col-xs-4">
            <h4><b class="title_2"> Client</b></h4>
        </div>
        <div class="col-xs-4">

        </div>
        <div class="col-xs-4">
            <h4><b class="title_2"> Vendor</b></h4>
        </div>
    </div>

    <div class="row" style="padding-top:2rem;">

        <div class="col-xs-6 left-cont">

            <p><b>


                    <h2><b class="invoice doc-type">QUOTATION</b></h2>
                    <p><b>{{ $data[0]->customer->company_name }}</b></p>

                    @if ($data[0]->customer->company_phone)
                        <p>Phone: {{ $data[0]->customer->company_phone }} </p>
                    @endif
                    @if ($data[0]->customer->company_email)
                        <p>Email: {{ $data[0]->customer->company_email }} </p>
                    @endif
                    @if ($data[0]->customer->country)
                        <p>Country: {{ $data[0]->customer->country }}/{{ $data[0]->customer->city }} </p>
                    @endif
                    @if ($data[0]->customer->postal_address)
                        <p>{{ $data[0]->customer->postal_address }} / {{ $data[0]->customer->address }} </p>
                    @endif
                    @if ($data[0]->customer->pin)
                        <p>Client PIN: {{ $data[0]->customer->pin }} </p>
                    @endif

                    <p class="item"> Quotation No: {{ $data[0]->order_no }}</p>



                    <p class="item"> Date: {{ $data[0]->order_date }}</p>


        </div>
        <div class="col-xs-2"></div>
        <div class="col-xs-4 right-cont">


            <h3>From</h3>
            <p> {{ $data[0]->branch->business_name }}</p>
            @if ($data[0]->branch->branch)
                <p>Branch: {{ $data[0]->branch->branch }}</p>
            @endif

            @if ($data[0]->branch->postal_address)
                <p>Address: {{ $data[0]->branch->postal_address }}</p>
            @endif
            @if ($data[0]->branch->address)
                <p> {{ $data[0]->branch->address }}</p>
            @endif
            @if ($data[0]->branch->kra_pin)
                <p>Document PIN: {{ $data[0]->branch->kra_pin }}</p>
            @endif
         
            <p> Generated By: {{ $data[0]->user->name }}</p>
            @if ($data[0]->branch->till_no)
            <div class="payment"> <b> {{ $data[0]->branch->till_no }}</b></div>
        @endif
        </div>

    </div>

    {{-- <div class="row">
        <div class="col-xs-12 invoice doc-type">
            <h3>INVOICE</h3>
        </div>
    </div> --}}

    <hr>
   

    <table class="table ">
        <thead class="bg-dark">
            <tr>
                <td><b class="title_2">Code</b></td>
                <td><b class="title_2">Item Name</b></td>
            
                <td><b class="title_2">Disc(%)</b></td>

                <td><b class="title_2">Qty</b></td>
                <td><b class="title_2">Price</b></td>
                <td><b class="title_2">Total</b></td>
            </tr>
        </thead>
        <tbody>
            @php($total = 0)
            @php($total_tax = 0)
            @php($total_discount = 0)
            @php($final_amount = 0)
            @foreach ($data as $item)
                <tr>
                    <td class="item">{{ $item->stock->code }}</td>
                    <td class="item">{{ $item->stock->product_name }}</td>
                  
                    <td class="item">{{ $item->discount }}</td>

                    <td class="item">{{ $item->qty }}</td>
                    <td class="item">{{ number_format($item->selling_price, 2) }}</td>
                    <td class="item">{{ number_format($item->row_total, 2) }}</td>
                    @php($total += $item->row_total)
                    @php($total_tax += $item->tax_amount)
                    @php($total_discount += $item->discount * $item->row_total*0.01)
                
                </tr>
            @endforeach

           @if ($total_discount > 0)
            <tr>
                <td colspan="5">
                    <b>Discount Amount</b>
                </td>
                <td>
                    <b> {{ number_format($total_discount, 2) }}</b>
                </td>
            </tr>
            @endif
          {{--    <tr>
                <td colspan="5">
                    <b>  Total Without Discount</b>
                </td>
                <td>
                    <b> {{ number_format($total, 2) }}</b>
                </td>
            </tr>
            @endif
            --}}

            <tr>
                <td colspan="5">
                    <b>Gross Total Amount </b>
                </td>
                <td>
                    <b> {{ number_format($total, 2) }}</b>
                </td>
            </tr>
        </tbody>
    </table>


</body>

</html>
