[
    {
        parent: "Dashboard",
        children: [
            {
                resourceName: "Dashboard",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "/",
            },
        ],
    },
    {
        parent: "Administration",
        children: [
            {
                resourceName: "Branches",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "branch",
            },
            {
                resourceName: "Departments",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "department",
            },
            {
                resourceName: "Tax",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "tax",
            },
            {
                resourceName: "Roles",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "roles",
            },
            {
                resourceName: "Assign Roles",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "assign_roles",
            },
            {
                resourceName: "Create Users",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "create_users",
            },
            {
                resourceName: "User Management",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "user_dashboard",
            },
            {
                resourceName: "Rooms Manager",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "rooms_standard_dashboard",
            },
            {
                resourceName: "Rooms Manager /Rooms",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "rooms",
            },
            {
                resourceName: "Rooms Manager /Accomodation Package",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "accomodation_package",
            },
            {
                resourceName: "Rooms Manager / Rates",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_rates",
            },
            {
                resourceName: "Locations",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "locations",
            },
            {
                resourceName: "Locations  Tables",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "tables",
            },
            {
                resourceName: "POS Settings",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "pos_settings",
            },
        ],
    },
    {
        parent: "Store",
        children: [
            {
                resourceName: "Stock Management",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "stock_management",
            },
            {
                resourceName: "Update Stock Balance",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "update_stock_balance",
            },
            {
                resourceName: "Update Stock Balance / Stock Deduction Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "stock_deduction_report",
            },
            {
                resourceName: "Update Stock Balance / Stock Update Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "physical_update_report",
            },
            {
                resourceName: "Issue Stock",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "issue_stock",
            },
            {
                resourceName: "Internal Issue Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "internal_issue_report",
            },
            {
                resourceName: "Internal Issue Report /Detailed report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "internal_issue_detailed_report",
            },
            {
                resourceName: "Stock Management /Add Product Category",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "create_product_category",
            },
            {
                resourceName: "Stock Management / Create Unit",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "create_unit",
            },
            {
                resourceName: "Stock Management / Split Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "split_products_report",
            },
            {
                resourceName: "Stock Management / StockTake Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "stocktake_report",
            },
            {
                resourceName: "Requisition",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "requisition",
            },
            {
                resourceName: "Approve Requisition",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "approve_requisition",
            },
            {
                resourceName: "Requisition / Assembly Product",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "assembly_product_requisition_dashboard",
            },
            {
                resourceName: "Requisition / Single Product",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "single_product_requisition_dashboard",
            },
            {
                resourceName: "Requisition / Dispatch Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "dispatch_report",
            },
            {
                resourceName: "Requisition / Stock Returns",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "stock_returns",
            },
            {
                resourceName: "Requisition / Returns Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "return_report",
            },
            {
                resourceName: "Purchase Orders",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "po_management",
            },
            {
                resourceName: "Stock Management /Purchases Delivery",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "order_delivery",
            },
            {
                resourceName: "Stock Management /Delivery Notes",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "delivery_notes",
            },
            {
                resourceName: "Stock Management /Orders Confirmation",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "confirm_orders",
            },
            {
                resourceName: "Stock Management /Orders Returns",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "purchase_returns",
            },
            {
                resourceName: "Direct Purchase",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "direct_purchase",
            },
            {
                resourceName:
                    "Direct Purchase / Direct Purchase Order Delivery",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "direct_order_delivery",
            },
            {
                resourceName:
                    "Direct Purchase / Direct Purchase Receivable Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "direct_order_delivery_report",
            },
            {
                resourceName: "Direct Purchase / Direct Purchase GRN",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "direct_grn",
            },
            {
                resourceName: "Stock Movt Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "stock_movement_report",
            },
            {
                resourceName: "Stock Movt Report /Movement Logs",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "stock_movement_logs",
            },
            {
                resourceName: "Department Stock Movt Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "department_stock_movt_report",
            },
            {
                resourceName: "Department Stock Movt Report /Movt Logs",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "department_stock_movt_logs",
            },
        ],
    },
    {
        parent: "Accounts",
        children: [
            {
                resourceName: "Accounts Receivable",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "accounts_receivable",
            },
            {
                resourceName: "Accounts Receivable / New Orders",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "orders_dashboard",
            },
            {
                resourceName: "Accounts Receivable / Invoices",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "invoices",
            },
            {
                resourceName: "Accounts Receivable / Opening Balance",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "new_opening_balances",
            },
            {
                resourceName: "Accounts Receivable / Payments",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "payments",
            },
            {
                resourceName: "Accounts Receivable / Add Payments",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "add_payment",
            },
            {
                resourceName: "Accounts Receivable / Credit Notes",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "credit_notes",
            },
            {
                resourceName: "Receivable Reports",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "invoice_reports",
            },
            {
                resourceName: "Receivable Reports /Payment Reports",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "payment_report",
            },
            {
                resourceName: "Receivable Reports /Customer Ledger",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "customer_ledger",
            },
            {
                resourceName: "Accounts Receivable",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "new_supplier_invoice",
            },
            {
                resourceName: "Accounts Receivable /Invoices Dashboard",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "supplier_invoices",
            },
            {
                resourceName: "Accounts Receivable /Supplier Payments",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "supplier_payments",
            },
            {
                resourceName: "Payable Reports",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "supplier_payment_report",
            },
            {
                resourceName: "Payable Reports /Supplier Statements",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "supplier_debts",
            },
            {
                resourceName: "Suppliers",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "suppliers",
            },
            {
                resourceName: "Customers",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "customers",
            },
            {
                resourceName: "Transactions",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "transaction",
            },
        ],
    },
    {
        parent: "Accommodation",
        children: [
            {
                resourceName: "Location Manager",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "locations",
            },
            {
                resourceName: " Rooms Manager",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "rooms_standard_dashboard",
            },
            {
                resourceName: "Guest Manager",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "guest_manager",
            },
            {
                resourceName: "Reserve Room",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "room_select",
            },
            {
                resourceName: "Reserve Room /Book Room",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "reservation",
            },
            {
                resourceName: "Room Checkout",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "room_checkout",
            },
            {
                resourceName: "Reservations Calendar Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "current_reservations_calendar",
            },
            {
                resourceName: "Reservations Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "current_reservations_tabular",
            },
            {
                resourceName: "Reservations Report / Daily Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "daily_accommodation_report",
            },
            {
                resourceName: "Reservations Report /Pending checkouts",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "fetch_pending_checkout",
            },
            {
                resourceName: "Reservations Report /Room Transfers",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_transfer_reports",
            },
            {
                resourceName: "HouseKeeping",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "housekeeping_dashboard",
            },
            {
                resourceName: "HouseKeeping / HouseKeeping Reservation report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "housekeeping_report",
            },
            {
                resourceName: "HouseKeeping /Room Maintainance",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "maintain_room",
            },
            {
                resourceName: "Reservation Balances",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "reservation_balances",
            },
            {
                resourceName: "Reservation Balances /Reception Balance Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "reservation_balances_report",
            },
        ],
    },
    {
        parent: "Payroll",
        children: [
            {
                resourceName: " Employee Manager",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "employee_manager",
            },
            {
                resourceName: "Payroll / Employee Roles",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "employee_roles",
            },
            {
                resourceName: " Production Manager",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "payroll_production",
            },
            {
                resourceName: "Payroll / Production Manager",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "payroll_product",
            },
            {
                resourceName: "Overtime",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "time_logs",
            },
            {
                resourceName: "Salary Sale Deduction",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "salary_sale_deduction",
            },
            {
                resourceName: "Casuals Time-Logs",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "casuals_timelogs",
            },
            {
                resourceName: "Loans",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "loans",
            },
            {
                resourceName: "Allowances",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "allowance",
            },
            {
                resourceName: "Deductions",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "deductions",
            },
            {
                resourceName: "Statutory",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "statutory",
            },
            {
                resourceName: "Advance",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "advance",
            },
            {
                resourceName: "Commissions/Rewards",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "reward",
            },
            {
                resourceName: "Generate Payslips",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "generate_payroll",
            },
            {
                resourceName: "Payslips",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "generic_payslips",
            },
        ],
    },
    {
        parent: "Conference",
        children: [
            {
                resourceName: "Conference Booking",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "conference_booking",
            },
            {
                resourceName: "C/ Booking Reports",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "conference_booking_report",
            },
        ],
    },
    {
        parent: "Point Of Sale",
        children: [
            {
                resourceName: "Point Of Sale",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "posmenu",
            },
            {
                resourceName: "Point Of Sale/ Dine In ",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "dine_in",
            },
            {
                resourceName: "Point Of Sale/ Dine Order ",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "create_dineorder",
            },
            {
                resourceName: "Point Of Sale/ Bills",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "bills",
            },
            {
                resourceName: "Point Of Sale/ View Bills",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "diner_bills",
            },
            {
                resourceName: "Point Of Sale/ Split Bills",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "split_bills",
            },
            {
                resourceName: "Point Of Sale/ Cashier",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "cashier_dashboard",
            },
            {
                resourceName: "Point Of Sale/ Uncleared Waiter Sales",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "uncleared_waiter_sales",
            },
            {
                resourceName: "Point Of Sale/ Merge Bill",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "merge_bill",
            },
            {
                resourceName: "Point Of Sale/ Room Service",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_service",
            },
            {
                resourceName: "Point Of Sale/ Room Orders",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_service_order",
            },
            {
                resourceName: "Point Of Sale/ Room Bills ",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_bills",
            },
            {
                resourceName: "Point Of Sale/ Room Bills Payment",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_bill_payments",
            },
            {
                resourceName: "Point Of Sale/ Room Bills Uncleared Payment",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "uncleared_room_service_sales",
            },
            {
                resourceName: "Point Of Sale /Merge Room Service Bill",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "merge_room_service_bills",
            },
            {
                resourceName: "Point Of Sale  /New Takeaway Orders",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "new_takeaway_orders",
            },
            {
                resourceName: "Point Of Sale  /TakeAway Bills",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "takeaway_bills",
            },
            {
                resourceName: "Cashier Orders",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "cashier_order",
            },
            {
                resourceName: "Cashier Orders / RoomService Orders",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_service_cashier",
            },
            {
                resourceName: "Waiter Bills/ Clear Waiter Bills",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "clear_waiter_bills",
            },
            {
                resourceName: "Waiter Bills/ Clear Waiter RS Payments",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "clear_waiter_rs_payments",
            },
            {
                resourceName: "Cashier Orders / Takeaway Orders",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "takeaway_cashier",
            },
            {
                resourceName: "Cashier Balances",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "cashier_balances_dashboard",
            },
            {
                resourceName: "Cashier Balances /Cashier Balance Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "balances_report",
            },
            {
                resourceName: "Point Of Sale Reports",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                name: "all_sales_reports",
            },
            {
                resourceName: "Point Of Sale Reports / Dine in",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "pos_reports",
            },
            {
                resourceName:
                    "Point Of Sale Reports /Sold Product Dining Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "diner_details_report",
            },
            {
                resourceName: "Point Of Sale Reports /Dinein Category Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "dine_category_report",
            },
            {
                resourceName: "Point Of Sale Reports /Room Service Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_service_sales_report",
            },
            {
                resourceName: "Point Of Sale Reports /Room Service Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "room_service_items_report",
            },
            {
                resourceName: "Point Of Sale Reports /Users Sale Summary",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "user_sale_summary",
            },
            {
                resourceName: "POS Report  /TakeAway Sales Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "take_away_sales_report",
            },
            {
                resourceName: "POS Report  /TakeAway Items Report",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "take_away_items_report",
            },
            {
                resourceName: "POS Report  /Employee Salary Sales",
                read: true,
                write: true,
                update: true,
                fetch: true,
                branch: true,
                approve: true,
                download: true,
                delete: true,
                menu_hide: true,
                name: "employee_sale_salary_deduction_report",
            },
        ],
    },
];
