<template>
    <div id="print_section">
        <div class="print-border">
            <div ref="contentToPrint">
                <div class="row">
                    <div class="col-md-12">
                        <center>
                            <h3
                                style="
                                    text-decoration: underline;
                                    text-align: center;
                                    font-weight: bold;
                                    margin-top: 2rem;
                                "
                            >
                            Item Movement History For {{ details_data.product_name }}
                            </h3>
                        </center>
                    </div>
                </div>
              

               
           
                <div :style="dynamicStyle"></div>
                <div class="row">
                    <div class="col-md-6">
                      
                    </div>
                </div>
                <div class="row" style="margin-left: 8px; margin-right: 8px">
                    <div class="col-md-12 mt-2 table-container">
                        <table class="table">
                            <thead>
                                <tr>
                        <th>ID</th>
                        <th scope="col">stock id</th>
                        <th scope="col">Ref</th>
                        <th>Movement Description</th>
                        <th scope="col">Qty</th>
                        <th scope="col">Date</th>
                      
                    </tr>
                            </thead>
                            <tbody>
                            <tr
                        class="small-tr"
                        v-for="(data, i) in print_data"
                        :key="i"
                    >
                    <td>{{data.id}}</td>
                        <td>{{ data.stock_id }}</td>

                        <td>
                            {{ data.ref}}
                        </td>
                        <td>{{data.table}}</td>
                        <td>
                            {{ (data.qty) }}
                        </td>
                        <td>
                           {{formatMonthDateTime(data.created_at)}}
                        </td>
                       
                          
                    </tr>
                             
                            </tbody>
                        </table>
                    </div>
                </div>
                <div
                    class="row"
                    style="
                        margin-top: 8rem;

                        margin-right: 2rem;
                        margin-left: 2rem;
                    "
                >
                   
                </div>
                <div class="row" style="bottom: 6rem; width: 100%">
                    <div class="col-md-12">
                        <div
                            style="
                                margin-top: 2rem;
                                border: 1px solid black;
                                margin-right: 2rem;
                                margin-left: 2rem;
                            "
                        ></div>
                        <div :style="dynamicStyle"></div>
                    </div>
                </div>
                <div class="row" style="bottom: 1rem; width: 90%">
                    <div class="col-md-12">
                        <div>
                            <p
                                style="
                                    display: inline-block;
                                    margin-left: 3rem;
                                    float: left;
                                "
                            >
                                Generated By:
                                {{ this.$store.state.user.name }}
                            </p>

                        </div>
                    </div>
                      
                </div>
            </div>
        </div>
    </div>
</template>

<script>


export default {
    components: {
  
    },
  props: ["print_data","details_data"],
    data() {
        return {
           
            publicPath: process.env.BASE_URL,
            borderColor: "#000000",
            imageWidth: this.$store.state.branch.logo_width,
            imageHeight: this.$store.state.branch.logo_height,
        };
    },
    created() {
        this.logo = this.$store.state.branch.img_url;
        this.borderColor = this.$store.state.branch.strip_color;
        //this.$store.state.branch.img_url
        const cssPath = window.location.origin + this.$route.path;
       
    },
    computed: {
        dynamicStyle() {
            return {
                marginTop: "1rem",
                marginBottom: "1rem",
                border: `1px solid ${this.borderColor}`,
                marginRight: "2rem",
                marginLeft: "2rem",
            };
        },
    },
    methods: {
        printBill: function () {
            const contentToPrint = this.$refs.contentToPrint;

            // Create a new window or iframe
            const printWindow = window.open("", "", "");

            // Write the content of the target div to the new window or iframe
            printWindow.document.open();
            printWindow.document.write(`
      <html>
        <head>
          <title>Print</title>
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
      
           
           <style>
       

 .top-table  table  tr, .top-table  table  tr td{
  border: 1px solid;

}
.table-title {
padding-left: 10px;padding-right: 10px;
}
.hr-line{
    height:8px;
    color:black;
}
.table {
max-height:100px !important;
    padding-bottom: 10rem; /* Adjust this value to match the height of your bottom strip */
}



           </style>
        </head>
        <body>
          ${contentToPrint.innerHTML}
        </body>
      </html>`);
            printWindow.document.close();

            // Print the new window or iframe
            setTimeout(() => {
                printWindow.print();
            }, 1000);
        },
    },
};
</script>
<style scoped>
/* #print_section {
    visibility: hidden;
} */
.border {
    border: 3px solid black !important;
}

/* .block-disp {
    display: block;
} */
.table-container {
    padding-bottom: 6rem; /* Adjust this value to match the height of your bottom strip */
}

.table-container .table tr {
    page-break-inside: avoid;
}

/* Styling for the bottom strip */
.bottom-strip {
    display: none;
}

/* Use @media print to control the display on the last page */
</style>
